# Generated by Django 2.2 on 2020-04-19 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20200414_2251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
