# Generated by Django 2.2 on 2020-04-19 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_delete_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
